name: demivolee
description: Demivolee companion application. Football news and comments.

author : betse <anon127nobody@gmail.com>
homepage: www.demivolee.com

version: 0.6.0+55

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1
  html_unescape: ^1.0.1+2
  transparent_image: ^0.1.0
  # flutter_launcher_icons: ^0.7.0
  flutter_custom_tabs: ^0.5.0
  firebase_core: ^0.3.1+1
  firebase_analytics: ^2.0.3
  firebase_performance: ^0.1.0+4
  firebase_admob: ^0.8.0+3
  admob_flutter: 
    path: "../admob_flutter/"
  # flutter_html: 
  #  path : "../flutter_html/"
  cached_network_image: ^0.6.2
  html: ^0.13.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: false
  image_path: "assets/logov2_round2.png"

flutter:
  uses-material-design: true

  assets:
  - assets/

  fonts:
    - family : Tw Cen MT
      fonts : 
        - asset : fonts/Tw Cen MT.ttf

    - family : Bebas Neue
      fonts :
        - asset : fonts/BebasNeue-Regular.ttf