name: demivolee
description: Demivolee companion application. Football news and comments.

author : betse <anon127nobody@gmail.com>
homepage: www.demivolee.com

version: 0.8.4+80

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1
  html_unescape: ^1.0.1+3
  transparent_image: ^1.0.0
  # flutter_launcher_icons: ^0.7.0
  flutter_custom_tabs: ^0.6.0
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.1
  firebase_performance: ^0.3.0+4
  firebase_admob: ^0.9.0+7
  admob_flutter: ^0.3.1
  #  path: "../admob_flutter/"
  #flutter_html: any 
  #  path : "../flutter_html/"
  cached_network_image: ^1.1.1
  html: ^0.13.4+1 #this
  webview_flutter:
    git: 
      url: git://github.com/devangels/plugins.git
      ref: cookies
      path: packages/webview_flutter
  firebase_crashlytics: ^0.1.0+3
  shared_preferences: ^0.5.3+4
  photo_view: ^0.5.0
  share: ^0.6.2+1
  uni_links: ^0.2.0
  provider: ^3.1.0
  flutter_webview_plugin: ^0.3.8
  flutter_inappbrowser: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: false
  image_path: "assets/logov2_round2.png"

flutter:
  uses-material-design: true

  assets:
  - assets/

  fonts:
    - family : Tw Cen MT
      fonts : 
        - asset : fonts/Tw Cen MT.ttf

    - family : Bebas Neue
      fonts :
        - asset : fonts/BebasNeue-Regular.ttf